version: '3'
services:
  database:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5400:5432
    volumes:
      - database:/var/lib/postgres/data
  api:
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    depends_on:
      - database
  frontend:
    build:
      context: './frontend'
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
  # nginx:
  #   build:
  #     context: './nginx'
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - api
volumes:
  database:
networks:
  external:
    name: local